version: 2
jobs:
  build-docker:
    docker:
      - image: docker:18.09.5-git
    environment:
      DOCKER_REPO: craigrueda/ring-slack
      ENV_FILE: /etc/envvars
    steps:
      - checkout
      - run:
          name: "Setup envars"
          command: |
            # Construct a "normalized" branch name from which we can build a Docker tag
            NORMALIZED_BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z_-]/z/g')
            SHORT_GIT_REV=$(git rev-parse --short HEAD)

            echo "export BRANCH_TAG=\"${DOCKER_REPO}:${NORMALIZED_BRANCH_NAME}-${SHORT_GIT_REV}\"" >> ${ENV_FILE}
            echo "export SHA_TAG=\"${DOCKER_REPO}:${CIRCLE_SHA1}\"" >> ${ENV_FILE}
            echo "export NORMALIZED_BRANCH_TAG=\"${DOCKER_REPO}:${NORMALIZED_BRANCH_NAME}\"" >> ${ENV_FILE}
      - run:
          name: "Build image"
          command: |
            source ${ENV_FILE}

            # Login first
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Actually build the thing...
            echo "Building with tags: [${BRANCH_TAG}, ${SHA_TAG}]"
            docker build \
                -t "${BRANCH_TAG}" \
                -t "${SHA_TAG}" \
                -t "${NORMALIZED_BRANCH_TAG}" \
                --label "ci.triggered_by=${CIRCLE_USERNAME}" \
                --label "ci.build_date=$(date)" \
                --label "ci.build_num=${CIRCLE_BUILD_NUM}" \
                --label "ci.build_url=${CIRCLE_BUILD_URL}" \
                --label "git.branch=${CIRCLE_BRANCH}" \
                --label "git.sha=${CIRCLE_SHA1}" \
                --label "git.url=${CIRCLE_REPOSITORY_URL}" \
                .
      - run:
          name: "Push image"
          command: |
            source ${ENV_FILE}

            # Login first
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Now push
            echo "Pushing tags: [${BRANCH_TAG}, ${SHA_TAG}]"
            docker push "${BRANCH_TAG}"
            docker push "${NORMALIZED_BRANCH_TAG}"
            docker push "${SHA_TAG}"
workflows:
  version: 2
  build-push:
    jobs:
      - build-docker
