version: 2
jobs:
  build-docker:
    docker:
      - image: docker:18.09.5-git
    environment:
      DOCKER_REPO: craigrueda/ring-slack
      ENV_FILE: /etc/envvars
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build images"
          command: |
            # Login first
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Build the x86 version...
            docker build \
                -t "${DOCKER_REPO}:latest" \
                --label "ci.triggered_by=${CIRCLE_USERNAME}" \
                --label "ci.build_date=$(date)" \
                --label "ci.build_num=${CIRCLE_BUILD_NUM}" \
                --label "ci.build_url=${CIRCLE_BUILD_URL}" \
                --label "git.branch=${CIRCLE_BRANCH}" \
                --label "git.sha=${CIRCLE_SHA1}" \
                --label "git.url=${CIRCLE_REPOSITORY_URL}" \
                .

            # Build the x86 version...
            docker build \
                -t "${DOCKER_REPO}:arm32v7" \
                --build-arg BASE_REPO=arm32v7 \
                --label "ci.triggered_by=${CIRCLE_USERNAME}" \
                --label "ci.build_date=$(date)" \
                --label "ci.build_num=${CIRCLE_BUILD_NUM}" \
                --label "ci.build_url=${CIRCLE_BUILD_URL}" \
                --label "git.branch=${CIRCLE_BRANCH}" \
                --label "git.sha=${CIRCLE_SHA1}" \
                --label "git.url=${CIRCLE_REPOSITORY_URL}" \
                .
      - run:
          name: "Push image"
          command: |
            # Login first
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Now push
            docker push "${DOCKER_REPO}:latest"
            docker push "${DOCKER_REPO}:arm32v7"
workflows:
  version: 2
  build-push:
    jobs:
      - build-docker
